import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {parseCSV,parseColors,backgroundFor,paletteFor} from '../src/lib/csv.js';import {parseCalendar,parseAnnual,activeOn,nextChange,resolve,periodsForYear,validRule} from '../src/lib/calendar.js';import {fromKey,key,addDays,difference,daysInYear,easter} from '../src/lib/dates.js';import {site} from '../src/config/site.js';import {messages} from '../src/i18n/messages.js';
const read=f=>readFileSync(new URL('../src/data/'+f,import.meta.url),'utf8');const rows=parseCalendar(read('calendar.csv')),annual=parseAnnual(read('annual-dates.csv'));const ids=s=>activeOn(rows,annual,fromKey(s)).map(p=>p.id);
test('upcoming skips Chuseok while preserving secondary recognition',()=>{
 for(const date of ['2026-09-01','2026-09-05']) {
  const next=nextChange(rows,annual,fromKey(date));
  assert.equal(key(next.date),'2026-09-07');
  assert.equal(next.added[0].id,'late-summer');
 }
 assert.ok(ids('2026-09-05').includes('chuseok'));
 for(const year of [2024,2025,2026,2027,2028]) {
  const period=periodsForYear(rows,annual,year).find(p=>p.id==='chuseok');
  for(const date of [addDays(period.start,-1),period.start,period.end]) {
   const next=nextChange(rows,annual,date);
   for(const field of ['active','added','ended'])assert.ok(!next[field].some(p=>p.id==='chuseok'));
  }
 }
});
for(const [date,yes,no] of [
 ['2026-01-01',['winter','holiday','new-year'],['autumn']],['2026-01-06',['winter','holiday','new-year'],[]],['2026-01-07',['winter'],['holiday','new-year']],['2026-02-14',['winter','valentine'],[]],['2026-02-15',['winter'],['valentine']],['2026-02-28',['winter'],[]],['2024-02-29',['winter'],[]],['2024-03-01',['winter','patrick'],[]],['2026-03-17',['winter','patrick'],[]],['2026-03-18',['winter','transition'],['patrick']],['2026-05-25',['spring','early-summer'],[]],['2026-06-19',['spring'],['juneteenth']],['2026-07-04',['summer','independence'],[]],['2026-07-05',['summer'],['independence']],['2026-09-07',['late-summer'],['summer']],['2026-09-30',['autumn'],[]],['2026-10-01',['autumn','halloween'],[]],['2026-10-31',['autumn','halloween'],[]],['2026-11-01',['autumn','thanksgiving'],['halloween']],['2026-11-26',['autumn','thanksgiving'],['holiday']],['2026-11-27',['autumn','holiday'],['thanksgiving']],['2026-11-30',['autumn','holiday'],[]],['2026-12-01',['autumn','holiday'],['winter']],['2026-12-21',['winter','holiday'],['autumn']],['2026-12-25',['winter','holiday'],['new-year']],['2026-12-26',['winter','holiday','new-year'],[]],['2026-12-31',['winter','holiday','new-year'],[]]
])test(`boundary ${date}`,()=>{const actual=ids(date);yes.forEach(id=>assert.ok(actual.includes(id),`${id} missing`));no.forEach(id=>assert.ok(!actual.includes(id),`${id} unexpected`));});
test('astronomical boundaries follow local calendar date',()=>{for(const [event,id,previous] of [['spring','spring','winter'],['summer','summer','spring'],['autumn','autumn','late-summer'],['winter','winter','autumn']]){const d=resolve(event,2026,annual);assert.ok(ids(key(d)).includes(id));assert.ok(ids(key(addDays(d,-1))).includes(previous));assert.ok(!ids(key(d)).includes(previous));}});
test('leap years, DST, and year rollover use calendar days',()=>{assert.equal(daysInYear(2024),366);assert.equal(daysInYear(2026),365);assert.equal(key(addDays(fromKey('2024-02-28'),1)),'2024-02-29');assert.equal(key(addDays(fromKey('2024-02-29'),1)),'2024-03-01');assert.equal(key(addDays(fromKey('2026-12-31'),1)),'2027-01-01');assert.equal(difference(fromKey('2026-03-09'),fromKey('2026-03-07')),2);assert.equal(fromKey('2026-02-29'),null);});
test('movable holidays and Korean 2027 lunar new year',()=>{assert.equal(key(easter(2026)),'2026-04-05');assert.equal(key(easter(2027)),'2027-03-28');assert.equal(key(resolve('lunar-new-year',2027,annual)),'2027-02-07');assert.ok(ids('2026-09-08').includes('chuseok'));assert.ok(ids('2026-04-05').includes('easter'));assert.ok(!ids('2026-04-06').includes('easter'));});
test('next change includes endings and cross-year reset',()=>{const n=nextChange(rows,annual,fromKey('2026-01-06'));assert.equal(key(n.date),'2026-01-07');assert.equal(n.days,1);assert.equal(n.ended.length,2);assert.equal(key(nextChange(rows,annual,fromKey('2026-12-31')).date),'2027-01-07');});
test('every supported day has exactly one broad season',()=>{for(let y=2024;y<=2028;y++)for(let i=0;i<daysInYear(y);i++){const d=addDays(fromKey(`${y}-01-01`),i);assert.equal(activeOn(rows,annual,d).filter(p=>p.category==='season').length,1,key(d));assert.notEqual(activeOn(rows,annual,d)[0]?.id,'chuseok',key(d));}});
test('CSV parses real files, multiline quotes, and malformed input',()=>{assert.equal(rows.length,18);assert.equal(parseCSV('a,b\r\n"hello, world","a ""quote""\nnext"')[0].b,'a "quote"\nnext');let warnings=[];assert.deepEqual(parseCSV('a,b\n"broken',s=>warnings.push(s)),[]);assert.ok(warnings.length);warnings=[];assert.equal(parseCalendar(read('calendar.csv')+read('calendar.csv').split('\n')[1]+'\n',s=>warnings.push(s)).length,18);assert.ok(warnings.some(s=>s.includes('duplicate')));assert.equal(validRule('02-30'),false);assert.equal(validRule('nonsense'),false);assert.equal(validRule('easter-14'),true);assert.equal(resolve('02-29',2026,annual),null);assert.equal(parseAnnual('year,event,date\n2026,spring,2026-02-30',()=>{}).size,0);});
test('all 366 daily palettes load, with validation and fallback',()=>{const colors=parseColors(read('daily-colors.csv'));assert.equal(colors.size,366);assert.ok(colors.has('2-29'));for(const row of colors.values())for(const mode of ['light','dark'])for(const field of ['background','text','slider_accent'])assert.match(row[`${mode}_${field}`],/^#[0-9A-F]{6}$/i);for(const mode of ['light','dark'])assert.equal(backgroundFor(new Map(),fromKey('2026-09-08'),mode,site.fallbackBackground),site.fallbackBackground[mode]);assert.equal(paletteFor(colors,fromKey('2024-02-29'),'light',site.fallbackPalette).text,colors.get('2-29').light_text);assert.deepEqual(paletteFor(new Map(),fromKey('2026-09-08'),'dark',site.fallbackPalette),site.fallbackPalette.dark);let warnings=[];const bad=parseColors('month,day,light_mode_color,dark_mode_color\n2,29,#123456,invalid\n2,29,,\n2,30,,',s=>warnings.push(s));assert.equal(bad.size,1);assert.equal(bad.get('2-29').dark_mode_color,'');assert.ok(warnings.some(s=>s.includes('duplicate')));assert.ok(warnings.some(s=>s.includes('invalid date')));assert.equal(backgroundFor(bad,fromKey('2024-02-29'),'light',site.fallbackBackground),'#123456');});
test('translations cover every UI key and populated calendar suggestion',()=>{const keys=Object.keys(messages.en);for(const lang of ['ko','ga'])assert.deepEqual(Object.keys(messages[lang]),keys);for(const row of rows)for(const lang of ['en','ko','ga']){assert.ok(row[`name_${lang}`]);assert.ok(row[`description_${lang}`]);for(const category of ['decor','food','activities','media'])if(row[`permissible_${category}_en`])assert.ok(row[`permissible_${category}_${lang}`]);}});
